/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Grille */

#ifndef _Included_Grille
#define _Included_Grille
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     Grille
 * Method:    grilleCreation
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_Grille_grilleCreation
  (JNIEnv *, jobject, jint);

/*
 * Class:     Grille
 * Method:    grilleDestruction
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Grille_grilleDestruction
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Grille
 * Method:    grilleAjouterPion
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_Grille_grilleAjouterPion
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     Grille
 * Method:    grilleCoupValide
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_Grille_grilleCoupValide
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     Grille
 * Method:    grilleVainqueur
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_Grille_grilleVainqueur
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Grille
 * Method:    grilleToTab
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_Grille_grilleToTab
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Grille
 * Method:    grilleToString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Grille_grilleToString
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Grille
 * Method:    grilleFromTab
 * Signature: ([I)J
 */
JNIEXPORT jlong JNICALL Java_Grille_grilleFromTab
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     Grille
 * Method:    grilleVoisinsNode
 * Signature: (JI[I)V
 */
JNIEXPORT jintArray JNICALL Java_Grille_grilleVoisinsNode
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     Grille
 * Method:    GrilleGetSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_Grille_grilleGetSize
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
