/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Hex */

#ifndef _Included_Test
#define _Included_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Hex
 * Method:    helloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Hex_helloWorld
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
