/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Hex */

#ifndef _Included_Hex
#define _Included_Hex
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Hex
 * Method:    helloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Hex_helloWorld
  (JNIEnv *, jclass);

/*
 * Class:     Hex
 * Method:    grilleCreation
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_Hex_grilleCreation
  (JNIEnv *, jobject, jint);

/*
 * Class:     Hex
 * Method:    grilleDestruction
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Hex_grilleDestruction
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Hex
 * Method:    grilleAjouterPion
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_Hex_grilleAjouterPion
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     Hex
 * Method:    grilleCoupValide
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_Hex_grilleCoupValide
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     Hex
 * Method:    grilleVainqueur
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_Hex_grilleVainqueur
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Hex
 * Method:    grilleToTab
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_Hex_grilleToTab
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Hex
 * Method:    grilleToString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Hex_grilleToString
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Hex
 * Method:    grilleFromTab
 * Signature: ([I)J
 */
JNIEXPORT jlong JNICALL Java_Hex_grilleFromTab
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     Hex
 * Method:    grilleVoisinsNode
 * Signature: (JI[I)V
 */
JNIEXPORT jintArray JNICALL Java_Hex_grilleVoisinsNode
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     Hex
 * Method:    GrilleGetSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_Hex_grilleGetSize
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
