/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Grille and Partie */

#ifndef _Included_Hex_jni
#define _Included_Hex_jni
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     Grille
 * Method:    grilleCreation
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_java_1hex_partie_Grille_grilleCreation
  (JNIEnv *, jobject, jint);

/*
 * Class:     Grille
 * Method:    grilleDestruction
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_java_1hex_partie_Grille_grilleDestruction
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Grille
 * Method:    grilleAjouterPion
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_java_1hex_partie_Grille_grilleAjouterPion
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     Grille
 * Method:    grilleCoupValide
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_java_1hex_partie_Grille_grilleCoupValide
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     Grille
 * Method:    grilleVainqueur
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_java_1hex_partie_Grille_grilleVainqueur
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Grille
 * Method:    grilleToTab
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_java_1hex_partie_Grille_grilleToTab
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Grille
 * Method:    grilleToString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_java_1hex_partie_Grille_grilleToString
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Grille
 * Method:    grilleFromTab
 * Signature: ([I)J
 */
JNIEXPORT jlong JNICALL Java_java_1hex_partie_Grille_grilleFromTab
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     Grille
 * Method:    grilleVoisinsNode
 * Signature: (JI[I)V
 */
JNIEXPORT jintArray JNICALL Java_java_1hex_partie_Grille_grilleVoisinsNode
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     Grille
 * Method:    GrilleGetSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_java_1hex_partie_Grille_grilleGetSize
  (JNIEnv *, jobject, jlong);
  
/*
 * Class:     Partie
 * Method:    sauvegarderPartie
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_java_1hex_partie_Partie_sauvegarderPartie
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     Partie
 * Method:    chargerPartie
 * Signature: (Ljava/lang/String;ILjava/lang/String;)J
 */
JNIEXPORT jstring JNICALL Java_java_1hex_partie_Partie_chargerPartie
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
